usethis::use_package("curl")
usethis::use_package("data.table")
usethis::use_package("gtools")
usethis::use_package("reshape2")
usethis::use_package("RAdwords")
usethis::use_package("XML")
usethis::use_package("xml2")
